# Generated by Django 5.2.3 on 2025-06-30 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_multi_agent_dungeon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PerceptionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('command', 'Command'), ('none', 'None')], default='none', max_length=20)),
                ('text', models.TextField()),
                ('delivered', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mad_multi_agent_dungeon.agent')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mad_multi_agent_dungeon.commandqueue')),
            ],
        ),
    ]
