# Generated by Django 5.2.3 on 2025-06-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mad_multi_agent_dungeon", "0003_perceptionqueue_source_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="phase",
            field=models.CharField(
                choices=[
                    ("thinking", "Thinking"),
                    ("acting", "Acting"),
                    ("prompting", "Prompting"),
                    ("idle", "Idle"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
