# Generated by Django 5.2.3 on 2025-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_multi_agent_dungeon', '0005_agentmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
