# Generated by Django 5.2.3 on 2025-07-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_multi_agent_dungeon', '0011_alter_llmqueue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
    ]
