# Generated by Django 5.2.3 on 2025-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mad_multi_agent_dungeon", "0014_llmapikey_usage_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmapikey",
            name="parameters",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
