# Generated by Django 5.2.3 on 2025-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mad_multi_agent_dungeon", "0015_llmapikey_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="perception_limit",
            field=models.IntegerField(default=5000),
        ),
    ]
